### ISSUE TITLE
Use argparse instead of optparse

### ISSUE THREAD

**Issue by Iansus** [maaaaz/nmaptocsv#10]
The `optparse` module is deprecated, as stated in Python official documentation:

```
Deprecated since version 2.7: The optparse module is deprecated and will not be developed further; development will continue with the argparse module.
```

You can switch to `argparse` which provides a similar set of features.

**Comment by maaaaz** [comment]
Hello @Iansus,
I'm keeping `optparse` as it is available on old Python versions, whereas `argparse` only appeared with the [2.7 version](https://github.com/python/cpython/blob/e9330e79419bf44c20cabeb2539e2c71e6af9e06/Misc/NEWS)

But I know `optparse` won't be supported in future 3.x versions so I will replace it soon.

Cheers

**Comment by maaaaz** [comment]
fixed in https://github.com/maaaaz/nmaptocsv/commit/3c0558bb110a9baac6c79109151f7466bfc1ee23
