### ISSUE TITLE
Feature Request: include hostname, not just fqdn

### ISSUE THREAD

**Issue by fishouttah20** [maaaaz/nmaptocsv#17]
Ability to include the rDNS record for the IP in the output results. This is often different than the host name and provides the true FQDN when scanning a list of hostnames. For instance:

Nmap scan report for ExampleHostname (1.1.1.1)
Host is up (0.010s latency).
rDNS record for 1.1.1.1: ExampleHostname.intranet.domain.com
PORT...

Great tool, thanks for releasing it.

**Comment by fishouttah20** [comment]
After looking at the data longer it appears the rDNS information is there, but the original hostname requested to be scanned isn't, so in the above example, ExampleHostname isn't in the file, which makes cross-referencing back to other reports that only have the original hostname impossible. Changing Issue title to reflect the ask. (Both hostname and rDNS record

**Comment by maaaaz** [comment]
Hello @fishouttah20,

There is now a `rdns` item in the format to use with the `-f` option to parse the rDNS records.

Cheers.

**Comment by fishouttah20** [comment]
Thanks!
