### ISSUE TITLE
Processing using XML file

### ISSUE THREAD

**Issue by zukkie777** [maaaaz/nmaptocsv#18]
Hello.

I did not succeed, I used an XML file as an input file.

Please teach me how to solve it.

-------------------------------------------------------------------------------------
[root@localhost nmaptocsv]# python nmaptocsv.py -x ../20180921090847.xml -o hoge.csv
Traceback (most recent call last):
  File "nmaptocsv.py", line 665, in <module>
    main()
  File "nmaptocsv.py", line 638, in main
    results = parse_xml(options.xml_input)
  File "nmaptocsv.py", line 520, in parse_xml
    IPs[new_host.get_ip_num_format()] = new_host
UnboundLocalError: local variable 'new_host' referenced before assignment

**Comment by maaaaz** [comment]
Hello,

Can you join your XML file to this issue please ?

**Comment by zukkie777** [comment]
Thank you very much.
I appreciate your support.

I deleted the XML storage location url.

> Thanks I downloaded the file, I'll take a look at this bug.

**Comment by maaaaz** [comment]
Fixed in the 1.5 version, run it with the `-S` option to have the script output.

Cheers.

**Comment by zukkie777** [comment]
Thank you. 
I confirmed that it works properly.
