### ISSUE TITLE
nmap -sc

### ISSUE THREAD

**Issue by itbelongsinamuseum** [maaaaz/nmaptocsv#19]
Hello,

It's a great tool, thank you !

However, I used your tool with nmap -sc option and it doesn't seem to work.

It will be interested to have a new column with this kind of information.

Hope someone will find time to improve that part ! 
Peace.

**Comment by maaaaz** [comment]
Hello,

Try adding the following option while executing the tool:
```
-S, --script        Adds the script column in output, alias for -f "ip-
                        fqdn-port-protocol-service-version-script"
``` 
Cheers.

**Comment by itbelongsinamuseum** [comment]
Woops, 

My bad...

So, this is a perfect tool !

Thx.
