### ISSUE TITLE
Service name/version

### ISSUE THREAD

**Issue by leebaird** [maaaaz/nmaptocsv#5]
The service name and version are not being parsed correctly.

**Comment by maaaaz** [comment]
Hello Lee,

As I'm working on the next version, could you give me examples (anonymize it if needed) of nmap results that are poorly parsed by nmaptocsv ?

Regards.

**Comment by leebaird** [comment]
That was 10 months ago. I had someone just build me something new.

**Comment by maaaaz** [comment]
Parsing consistency has been improved with v1.1.

Cheers.
