### ISSUE TITLE
feature suggestion: Parse and normalize script output 

### ISSUE THREAD

**Issue by royharoush** [maaaaz/nmaptocsv#7]
Hi,
Neat script !
Could you have it to also parse for script output and normalize the output for multiple scripts. 
for instance, if you have multiple script running, then create a column for each script output, and be able to configure additional columns from the script output (if a script outputs ASN: 51654, so make it possible have it change the ":" delimiter into a ","). (i know this can be done with some simple bash utils, like tr, awk and sed, but it would be simpler if you add to your code then me diving into it). 

Thanks,
Roy

**Comment by Maleus** [comment]
Bump! Came to make the same request

**Comment by maaaaz** [comment]
Hello @royharoush and @Maleus,

I implemented that feature in the lastest version (try `pip install nmaptocsv`)
I haven't made put item in the default format, so you have to add `script` to the `-f` parameter, like:
```
$ nmaptocsv -i <file> -f ip-fqdn-port-protocol-service-version-script
```

Tell me if it is working for you !

Cheers.
